### ISSUE TITLE
Build error with no helpful information at all

### ISSUE THREAD

**Issue by taylornelms15** [CIS565-Fall-2019/Project2-Number-Algorithms#1]
After changing the `sm_20` to a relevant version for the stream compaction part of the project, I've encountered the following error with very little to go off of:

    1>Building NVCC (Device) object stream_compaction/CMakeFiles/stream_compaction.dir/Debug/stream_compaction_generated_common.cu.obj
    1>CMake Error at stream_compaction_generated_common.cu.obj.cmake:206 (message):
    1>  Error generating
    1>  C:/Users/taylo/csworkspace/cis565/Project2/Project2-Stream-Compaction/build/stream_compaction/CMakeFiles/stream_compaction.dir//Debug/stream_compaction_generated_common.cu.obj
    1>
    1>
    1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(220,5): error MSB6006: "cmd.exe" exited with code 1.
    1>Done building project "stream_compaction.vcxproj" -- FAILED.

Might there be a solution to this sort of thing somewhere?

**Comment by hanbollar** [comment]
closing this issue since this was asked in the wrong location - it should be a piazza post instead.
